### ISSUE TITLE
Get requests work great, is remote_request implemented yet in the NA code?

### ISSUE THREAD

**Issue by 78hawkeye** [widewing/toyota-na#1] opened 2022-01-06 01:03 UTC
Hmmmmm, I can authenticate with no issue at all, and I can retrieve all sorts of cool data with the various get arguments.  But when I try any of the remote_request commands, I get what appear to be successful responses but nothing happens at the vehicle.  Is remote_request not implemented yet in the library?  Or is there another problem at play possibly that I should keep working on?

When I send:

`python -m toyota_na.app remote_request VIN engine-start`

and subbing in my VIN for a 2021 Tacoma

```
INFO 2022-01-05 19:53:27,655 - Response status: {'messages': [{'responseCode': 'ONE-GLOBAL-RS-10000', 'description': 'Request Completed Successfully', 'detailedDescription': 'Request Completed Successfully'}]}
{
  "appRequestNo": "ef4818c6-fd8b-3d03-aa59-709638445583",
  "correlationId": "05b53274-adf9-486d-a859-26ec8d567e49",
  "returnCode": "000000"
}
```

Fantastic work on the code, widewing!  Thanks for your efforts!

**Comment by johndbritton** [comment] 2022-01-06 02:05
I came here to make literally the same issue.

Running the following:
`python -m toyota_na.app remote_request <VIN> engine-start`

I get this output:
```
INFO 2022-01-05 21:03:15,837 - Response status: {'messages': [{'responseCode': 'ONE-GLOBAL-RS-10000', 'description': 'Request Completed Successfully', 'detailedDescription': 'Request Completed Successfully'}]}
{
  "appRequestNo": "51830071-abb4-3854-b246-d06ebfd942f9",
  "correlationId": "520e169e-dd6e-46b1-8894-adacc2e65640",
  "returnCode": "000000"
}
```

**Comment by widewing** [comment] 2022-01-06 05:16
yes the remote command is not working yet... it may require some more steps to actually trigger the remote command instead of just calling a single API.

**Comment by widewing** [comment] 2022-01-06 05:46
BTW the refresh_status command also not working, it's using the same API as the remote command. So one issue here is the door/window status not always up to date. In Toyota app, sometimes you need to click the refresh status button to manually update the status.

**Comment by johndbritton** [comment] 2022-01-10 00:37
@widewing I'm willing to put some time into this, any idea what's needed? Do you have a way to view inspect the requests that the mobile app is making so that we can reverse engineer the remote start command?

**Comment by widewing** [comment] 2022-01-10 06:31
> @widewing I'm willing to put some time into this, any idea what's needed? Do you have a way to view inspect the requests that the mobile app is making so that we can reverse engineer the remote start command?

No.. the mobile app will check your network so it will be hard to intercept requests. I was just looking into decompiled code to guess what the requests looks like. As a starting point, you can check `sources\com\toyota\oneapp\network\api` folder.

**Comment by JiDoan** [comment] 2022-01-10 08:48
I'm able to snoop some endpoints on iOS but the app starts behaving oddly when I enable snooping. I was able to glean some information, however.

It seems that the current implementation of `send_refresh_status` is missing the body. If I change the `send_refresh_status` body to contain the following, it appears to force an update judging by the response value of `occurrenceDate`.

```
    self.api_post("/v1/global/remote/refresh-status", {
            "guid": await self.auth.get_guid(),
            "deviceId": <64 character wide lowercase hex string>,
            "vin": vin,
            "deviceType": "iOS",
        }, {"VIN": vin})
```

I'm not sure where `deviceId` comes from but it appears to be a 64 character wide lowercase hex string. I tried putting in a random value (e.g. `87c6d07455a3b95a06a17fa257c2f5e2ce6ea15902ae0be400722c50d1e45c57`) and it appears to work the same compared to using the value intercepted from my device.

I can't quite verify if this is really doing anything yet since my car is in the shop but I can try playing around more when I get it back and have some free time.

**Comment by 78hawkeye** [comment] 2022-01-12 01:00
> @widewing I'm willing to put some time into this, any idea what's needed? Do you have a way to view inspect the requests that the mobile app is making so that we can reverse engineer the remote start command?

I tried setting up an SSL proxy in postman to catch the api calls from the ios app, but unfortunately the ios app uses SSL pinning to confirm it is talking with the toyota servers and will not interact with the proxy.  Not sure if anyone savvy on android could maybe get around any ssl pinning that might be on the android app and catch the api calls that way?

**Comment by JiDoan** [comment] 2022-01-19 08:07
I managed to figure out sending a command and was able to unlock/lock my doors using the API! Try it out with my pull request: #3

**Comment by 78hawkeye** [comment] 2022-01-19 21:01
> I managed to figure out sending a command and was able to unlock/lock my doors using the API! Try it out with my pull request: #3

Yes!  With those updates, I just successfully sent an engine-start and an engine-stop!  Awesome work, @JiDoan !!  Just in time for our next snow tonight.  :-)

**Comment by widewing** [comment] 2022-01-19 22:25
Thanks! It works for me too! I merged the PR.

**Comment by vanstinator** [comment] 2022-01-28 14:10
This should be working as intended. Feel free to file a new issue and tag it as a bug if you run in to problems.

CY17 vehicle support should land in the next week or two as we bring up a better API abstraction layer.

**Closed by vanstinator** 2022-01-28 14:10 UTC
